# Generated by Django 4.2.5 on 2023-09-29 14:46

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video/%Y-%m-%d', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
